const assert = require('assert');
const { makeRoom, addPlayer, timelineOutcomeState, TIMELINE_OUTCOMES } = require('../lib/game');
const room=makeRoom('STEP601');
const p=addPlayer(room);
p.reality='PAST';
assert.strictEqual(timelineOutcomeState(room,p).status,'LOCKED');
assert.ok(TIMELINE_OUTCOMES.PRESERVE && TIMELINE_OUTCOMES.ALTER);
console.log('CHRONO PARADOX Step 6 tests: PASS');
const { startGame, toggleReady, advanceTemporalEvent, castTimelineVote } = require('../lib/game');
const room2=makeRoom('ALTER01');
const ps=[addPlayer(room2),addPlayer(room2),addPlayer(room2),addPlayer(room2)];
ps.slice(0,2).forEach(x=>toggleReady(room2,x.id));
startGame(room2,ps[0].id);
for(const x of ps) advanceTemporalEvent(room2,x.id);
for(const x of ps) castTimelineVote(room2,x.id,'ALTER');
const alterOutcome=timelineOutcomeState(room2,ps[2]);
assert.strictEqual(alterOutcome.status,'RESOLVED');
assert.strictEqual(alterOutcome.choice,'ALTER');
assert.strictEqual(alterOutcome.state,'BRANCHED PATH');
console.log('CHRONO PARADOX Step 6 ALTER branch test: PASS');
